export const FETCH_CAR_LIST = 'FETCH_CAR_LIST';
export const FETCH_CAR_DETAILS = 'FETCH_CAR_DETAILS';
export const FETCH_COLOR_FILTER = 'FETCH_COLOR_FILTER';
export const FETCH_MANUFACTURER_FILTER = 'FETCH_MANUFACTURER_FILTER';

